### ISSUE TITLE
Fluency 1.0.9 doesn't work anymore - 1.0.7 does

### ISSUE THREAD

**Issue by nurkka** [SkyLundy/Fluency#10]
When using Fluency 1.0.9, instead of the translated string, I always get "undefined". In the log, it says: 

Engine: DeepLEngine /Error: BAD_REQUEST /Message: Invalid request: Expected 'text' parameter to be an array of strings /Response: {"message":"Invalid request: Expected 'text' parameter to be an array of strings"}

I downgraded to Fluency 1.0.7 and now it works again.

Using ProcessWire 3.0.240 with PHP 8.2. All ProcessWire Language Modules installed, 2 Languages configured: German as default, English as second language.

**Comment by SkyLundy** [comment]
Can you try downloading from the dev version and manually installing? Let me know if that fixes it. I think there are fixes that should help and I will push a new release on main if so.

**Comment by nurkka** [comment]
I just found the hint to the dev version in the forum:
https://processwire.com/talk/topic/24567-fluency-the-complete-translation-enhancement-suite-for-processwire/?do=findComment&comment=243081

After installing, it did not work instantly. I the installed ProcessCacheControl, configured it to clear all caches, also deleted the Fluency entries in the DB table pages_meta. Then I also logged out and in again - and after that, Fluency worked again :-)

**Comment by SkyLundy** [comment]
@nurkka Glad to be of some help. I've been having some trouble resolving inconsistent issues when upgrading. Sometimes there are problems, sometimes not.

I'm adding some notes to the README and will make another post in the forums that recommends a full uninstall and reinstall of the module for versions before 1.0.8.

Pushing a new version to main. Thanks!
