### ISSUE TITLE
Permission missing in the module’s info

### ISSUE THREAD

**Issue by romaincazier** [SkyLundy/Fluency#2]
Hi @SkyLundy,

In order for a non-superuser to be able to use the “Translation” modal, you not only need to set the `fluency-translate` in one of the user’s role but you also need to specify it in the module’s info, like so:

```
'permission' => 'fluency-translate',
'permissions' => [
    'fluency-translate' => __('Use Fluency translation')
],
```

See [ProcessHello.info.php#L41](https://github.com/ryancramerdesign/ProcessHello/blob/189029f494870760107d8a621dfb5a59db53959c/ProcessHello.info.php#L41)

**Comment by SkyLundy** [comment]
Can't believe I missed this... thanks!

Fix pushed in commit 13d50c7
