### ISSUE TITLE
Fatal errors if php > php 8.3.4

### ISSUE THREAD

**Issue by theoretic** [SkyLundy/Fluency#6]
**Issue:** multiple fatal errors in PW admin. Example of PW debug info:

`Uncaught Error: Undefined constant "Fluency\Engines\DeepL\CURLOPT_CONNECTTIMEOUT" in site/modules/Fluency/app/Engines/DeepL/DeepLEngine.php:220`

**How to reproduce**

- Install Fluency (any method)
- Go to Fluency module page or Fluency module settings page

 **Software configuration**

- PW 3.0.238+
- PHP 8.3.7

**Extra notes**

It appears that the issue is related to how php 8.3.7 handles arrays. Quote from site/modules/Fluency/app/Engines/DeepL/DeepLEngine.php:

`
    $requestConfig = [
      CURLOPT_CONNECTTIMEOUT => 5,
`

Here CURLOPT_CONNECTTIMEOUT looks like a constant. PHP 8.3.4 can however handle this type of array initialization, PHP 8.3.7 fails (at least at my Ubuntu production server).

**Comment by SkyLundy** [comment]
Thanks for reporting and the detailed information. I'll work on this and push a fix.

**Comment by SkyLundy** [comment]
I bumped to 8.3 and am not able to replicate the issue. Can you check to make sure that CURL is installed? `phpinfo()` will show details on that under the "CURL" section.

![Screenshot from 2024-05-28 10-14-38](https://github.com/SkyLundy/Fluency/assets/61801600/bb932789-c34e-4795-8854-516056183091)

**Comment by theoretic** [comment]
You win! ;) My php 8.3.7 at production server doesn't have CURL at all. Will try to add it.

**Comment by SkyLundy** [comment]
Ha, _we_ win. I'm glad I could help!
